apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: clienteapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: clienteapi
    spec:
      containers:
      - name: clienteapi
        image: registry.ng.bluemix.net/pruebacontenedorespbarrien/clienteapi2:1
