apiVersion: v1
kind: Service
metadata:
  name: clienteapi
  namespace: default

spec:
  ports:
  - nodePort: 32563
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: clienteapi
  sessionAffinity: None
  type: NodePort

